name: tekartik_aliyun_tablestore_sembast
description: Tablestore mock implementation
version: 0.2.3
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_aliyun_tablestore:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/tablestore
      ref: dart3a
    version: '>=0.2.3'
  sembast: ">=3.7.4+3"
  path: ">=1.9.0"
dev_dependencies:
  test: ">=1.24.0"

resolution: workspace
