name: tekartik_aliyun_tablestore_sembast
description: Tablestore mock implementation
version: 0.2.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  tekartik_aliyun_tablestore:
    git:
      url: git://github.com/tekartik/aliyun.dart
      path: common/tablestore
      ref: dart2
    version: '>=0.1.0'
  sembast:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

dependency_overrides:
  tekartik_aliyun_tablestore:
    path: ../tablestore
