name: tekartik_aliyun_repo
description: Aliyun cloud lib repo (tools)
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.8.0 <3.0.0'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: '>=0.13-3-dev.3'
  grinder:
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.5.8'
  process_run: '>=0.10.2'

dependency_overrides:
  dev_test:
    git:
      url: git://github.com/tekartik/dev_test.dart
      path: dev_test
      ref: develop
    version: '>=0.13.3+2'