name: tekartik_aliyun_oss
description: OSS base API
version: 0.2.2
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  meta:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart2_3
    version: '>=0.5.5'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.10.14'
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  dev_test:
