name: tekartik_aliyun_fc
description: Abstract Function Compute binding
version: 0.2.1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  path: ">=1.9.0"
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart3a
    version: '>=0.2.0+2'
dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace
