name: tekartik_aliyun_fc
description: Abstract Function Compute binding
version: 0.2.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  tekartik_http:
    git:
      url: git://github.com/tekartik/http.dart
      path: http
      ref: null_safety
    version: '>=0.2.0+2'
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
