name: tekartik_aliyun_tablestore_universal
description: Tablestore
version: 0.2.3
publish_to: none

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  tekartik_aliyun_tablestore:
    git:
      url: git://github.com/tekartik/aliyun.dart
      path: common/tablestore
      ref: dart2
    version: '>=0.2.3'
  tekartik_aliyun_tablestore_node:
    git:
      url: git://github.com/tekartik/aliyun.dart
      path: node/tablestore_node
      ref: dart2
    version: '>=0.2.3'
  tekartik_aliyun_tablestore_sembast:
    git:
      url: git://github.com/tekartik/aliyun.dart
      path: common/tablestore_sembast
      ref: dart2
    version: '>=0.2.3'
  dev_test: '>=0.13.3-dev.1'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  # Need for app node build
  tekartik_app_node_build:
    git:
      url: git://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart2
    version: '>=0.1.0'
  # Needed direct node dependencies
  build_node_compilers:
  build_runner:

dependency_overrides:
  tekartik_aliyun_tablestore:
    path: ../tablestore
  tekartik_aliyun_tablestore_node:
    path: ../../node/tablestore_node
  tekartik_aliyun_tablestore_sembast:
    path: ../../common/tablestore_sembast