name: tekartik_aliyun_tablestore_universal
description: Tablestore
version: 0.2.3
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_aliyun_tablestore:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/tablestore
      ref: dart3a
    version: '>=0.2.3'
  tekartik_aliyun_tablestore_node:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: node/tablestore_node
      ref: dart3a
    version: '>=0.2.3'
  tekartik_aliyun_tablestore_sembast:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/tablestore_sembast
      ref: dart3a
    version: '>=0.2.3'
  dev_build: '>=0.13.3-dev.1'

dev_dependencies:

  test: '>=1.14.4'
  # needed node dev dependencies
  build_runner:
  build_web_compilers:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a

resolution: workspace
