name: tekartik_aliyun_tablestore_universal
description: Tablestore
version: 0.1.0

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  tekartik_aliyun_tablestore:
    path: ../tablestore
  tekartik_app_node_build:
    git:
      url: git://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart2
    version: '>=0.1.0'
  tekartik_aliyun_tablestore_node:
    path: ../../node/tablestore_node
  tekartik_aliyun_tablestore_sembast:
    path: ../../common/tablestore_sembast

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  # Needed direct node dependencies
  build_node_compilers:
  build_runner:
