name: tekartik_aliyun_tablestore_universal
description: Tablestore
version: 0.2.3
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  tekartik_aliyun_tablestore:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/tablestore
      ref: dart3a
    version: '>=0.2.3'
  tekartik_aliyun_tablestore_node:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: node/tablestore_node
      ref: dart3a
    version: '>=0.2.3'
  tekartik_aliyun_tablestore_sembast:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/tablestore_sembast
      ref: dart3a
    version: '>=0.2.3'
  dev_build: ">=1.1.2"

dev_dependencies:

  test: ">=1.24.0"
  # needed node dev dependencies
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a

resolution: workspace
