name: tekartik_aliyun_oss_node
description: Aliyun oss node access
version: 0.3.1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  tekartik_aliyun_oss:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/oss
      ref: dart2_3
    version: '>=0.2.0'
  collection:
  tekartik_app_node_utils:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: node_utils
      ref: dart2_3
    version: '>=0.1.0'
  node_interop:
  js:
dev_dependencies:
  dev_test: '>=0.13.3-dev.1'

  test: ^1.14.4
  # needed node dependencies
  build_runner:
  build_web_compilers:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart2_3

dependency_overrides:
  tekartik_aliyun_oss:
    path: ../../common/oss
