targets:
  $default:
    sources:
      - "$package$"
      - "lib/**"
      - "bin/**"
      - "test/**"
      - "local_bin/**"
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - bin/**
          - local_bin/**
        options:
          compiler: dart2js