name: tekartik_aliyun_ts_node_min_example
description: A sample command-line application.
publish_to: none
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  path: ^1.7.0
  tekartik_aliyun_tablestore_universal:
    path: ../../../common/tablestore_universal

dev_dependencies:

  test: ^1.14.4
  # Aliyun function build
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart2_3
    version: '>=0.1.0'
  # needed node dev dependencies
  build_runner:
  build_web_compilers:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart2_3

dependency_overrides:
  tekartik_aliyun_tablestore:
    path: ../../../common/tablestore
  tekartik_aliyun_tablestore_node:
    path: ../../../node/tablestore_node
  tekartik_aliyun_tablestore_sembast:
    path: ../../../common/tablestore_sembast
