name: tekartik_aliyun_fc_node
description: A starting point for Dart libraries or applications.
version: 0.2.2
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  path: ^1.7.0
  tekartik_app_node_utils:
    git:
      url: git://github.com/tekartik/app_node_utils.dart
      path: node_utils
      ref: dart2
    version: '>=0.1.0'
  tekartik_aliyun_fc:
    git:
      url: git://github.com/tekartik/aliyun.dart
      path: common/fc
      ref: dart2
    version: '>=0.2.1'
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner:

dependency_overrides:
  tekartik_aliyun_fc:
    path: ../../common/fc