name: tekartik_aliyun_fc_node
description: A starting point for Dart libraries or applications.
version: 0.2.2+1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ^3.5.0

dependencies:
  path: '>=1.8.0'
  tekartik_app_node_utils:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: node_utils
      ref: dart3a
    version: '>=0.1.0'
  tekartik_aliyun_fc:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/fc
      ref: dart3a
    version: '>=0.2.1'
  js:
  node_interop:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.14'
  tekartik_js_utils:
    git:
      url: https://github.com/tekartik/js_utils.dart
      ref: dart3a
      path: js_utils
    version: '>=0.1.0'
dev_dependencies:

  test: '>=1.14.4'
  # needed node dependencies
  build_runner:
  build_web_compilers:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a

resolution: workspace
