name: tekartik_aliyun_fc_node
description: A starting point for Dart libraries or applications.
version: 0.2.2
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  tekartik_app_node_utils:
    git:
      url: git://github.com/tekartik/app_node_utils.dart
      path: node_utils
      ref: null_safety
    version: '>=0.1.0'
  tekartik_aliyun_fc:
    git:
      url: git://github.com/tekartik/aliyun.dart
      path: common/fc
      ref: null_safety
    version: '>=0.2.1'
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  # needed node dependencies
  build_runner:
  build_web_compilers:
  tekartik_build_node:
    git:
      url: git://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: null_safety

dependency_overrides:
  tekartik_aliyun_fc:
    path: ../../common/fc