name: tekartik_aliyun_cli
description: Aliyun command-line utilities (oss).
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.14'
  process_run: '>=0.11.0+1'
  synchronized:

dev_dependencies:
  test: '>=1.14.4'

resolution: workspace
