name: tekartik_aliyun_cli
description: Aliyun command-line utilities (oss).
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.10.14'
  process_run: '>=0.11.0+1'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
