name: tekartik_aliyun_tablestore_node
description: Aliyun tablestore node access
version: 0.2.5
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ^3.9.0

dependencies:
  path: ">=1.9.0"
  tekartik_aliyun_tablestore:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/tablestore
      ref: dart3a
    version: '>=0.2.3'
  collection: ">=1.18.0"
  tekartik_app_node_utils:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: node_utils
      ref: dart3a
    version: '>=0.1.0'
  js:
  node_interop:
  cv: ">=1.1.0+4"
  tekartik_js_utils:
    git:
      url: https://github.com/tekartik/js_utils.dart
      ref: dart3a
      path: js_utils
dev_dependencies:
  dev_build: ">=1.1.2"

  test: ">=1.24.0"
  # needed node dev dependencies
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a

resolution: workspace
