name: tekartik_aliyun_tablestore_node
description: Aliyun tablestore node access
version: 0.2.5
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  path: ^1.7.0
  tekartik_aliyun_tablestore:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/tablestore
      ref: dart2_3
    version: '>=0.2.3'
  collection:
  tekartik_app_node_utils:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: node_utils
      ref: dart2_3
    version: '>=0.1.0'
  js:
  node_interop:
  cv:
dev_dependencies:
  dev_test: '>=0.13.3-dev.1'

  test: ^1.14.4
  # needed node dev dependencies
  build_runner:
  build_web_compilers:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart2_3

dependency_overrides:
  tekartik_aliyun_tablestore:
    path: ../../common/tablestore