name: fc_node_simple_example
description: A simple log request.
publish_to: none
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tekartik_aliyun_fc_universal:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/fc_universal
      ref: dart2_3
    version: '>=0.1.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  # Aliyun function build
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart2_3
    version: '>=0.1.0'
  # needed node dev dependencies
  build_runner:
  build_web_compilers:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart2_3

dependency_overrides:
  tekartik_aliyun_fc_universal:
    path: ../../../common/fc_universal
  tekartik_aliyun_fc_node:
    path: ../../../node/fc_node
  tekartik_aliyun_fc_http:
    path: ../../../common/fc_http
  tekartik_aliyun_fc:
    path: ../../../common/fc