# tekartik analysis_options extension to pedantic
include: package:tekartik_lints/strict.yaml

linter:
  rules:
    avoid_print: true
    depend_on_referenced_packages: false

analyzer:
  exclude:
    - build/**