name: tekartik_aliyun_oss_universal
description: Aliyun OSS support (+ mock)
version: 0.1.3
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  path: ^1.7.0
  tekartik_app_node_build:
    git:
      url: git://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart2
    version: '>=0.1.0'
  tekartik_aliyun_oss:
    git:
      url: git://github.com/tekartik/aliyun.dart
      path: common/oss
      ref: dart2
    version: '>=0.1.1'
  tekartik_aliyun_oss_node:
    git:
      url: git://github.com/tekartik/aliyun.dart
      path: node/oss_node
      ref: dart2
    version: '>=0.1.1'
  tekartik_aliyun_oss_fs:
    git:
      url: git://github.com/tekartik/aliyun.dart
      path: common/oss_fs
      ref: dart2
    version: '>=0.1.4'
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

dependency_overrides:
  tekartik_aliyun_oss_node:
    path: ../../node/oss_node
  tekartik_aliyun_oss:
    path: ../oss
  tekartik_aliyun_oss_fs:
    path: ../oss_fs
