name: tekartik_aliyun_oss_universal
description: Aliyun OSS support (+ mock)
version: 0.3.1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ^3.7.0

dependencies:
  path: ">=1.9.0"
  tekartik_aliyun_oss:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/oss
      ref: dart3a
    version: '>=0.1.1'
  tekartik_aliyun_oss_node:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: node/oss_node
      ref: dart3a
    version: '>=0.3.1'
  tekartik_aliyun_oss_fs:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/oss_fs
      ref: dart3a
    version: '>=0.3.1'
dev_dependencies:
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  # needed node dev dependencies
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a

resolution: workspace
