name: fc_node_raw_example
description: A simple log request.
publish_to: none
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  node_interop:

dev_dependencies:
  lints:
  test: ^1.14.4
  # needed node dev dependencies
  build_runner:
  build_web_compilers:
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart2_3
