name: fc_node_raw_example
description: A simple log request.
publish_to: none
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.8.0

dependencies:
  node_interop:
  process_run: ">=1.2.1+1"
  path: ">=1.9.0"
dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
  # needed node dev dependencies
  build_runner: ">=2.4.13"
  build_web_compilers: ">=4.0.11"
  tekartik_build_node:
    git:
      url: https://github.com/tekartik/build_node.dart
      path: packages/build_node
      ref: dart3a
  tekartik_app_node_build:
    git:
      url: https://github.com/tekartik/app_node_utils.dart
      path: app_build
      ref: dart3a
    version: '>=0.1.0'
resolution: workspace
