ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  tekartik_fc_node:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: 'Function compute dart raw js'
    fc_node_basic:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs12
        CodeUri: './'
        Timeout: 10
      Events:
        httpTrigger:
          Type: HTTP
          Properties:
            AuthType: ANONYMOUS
            Methods: [ 'POST', 'GET' ]
