name: app_node_utils_repo_support
description: Mustache repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: '>=1.0.0'
  dev_build: '>=0.13.0'
  path:
  pub_semver:
  process_run:

resolution: workspace

