name: app_node_utils_repo_support
description: Mustache repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  lints: ">=5.0.0"
  dev_build: ">=1.1.2"
  path: ">=1.9.0"
  pub_semver: ">=2.1.4"
  process_run: ">=1.2.1+1"

resolution: workspace

