name: tekartik_aliyun_oss_fs
description: Tablestore mock implementation
version: 0.3.1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  tekartik_aliyun_oss:
    git:
      url: https://github.com/tekartik/aliyun.dart
      path: common/oss
      ref: dart3a
    version: '>=0.1.0'
  fs_shim: '>=1.0.2'
  cv:
  path:
dev_dependencies:
  test: '>=1.14.4'

dependency_overrides:
  tekartik_aliyun_oss:
    path: ../oss
