name: tekartik_aliyun_oss_fs
description: Tablestore mock implementation
version: 0.2.1
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  tekartik_aliyun_oss:
    git:
      url: git://github.com/tekartik/aliyun.dart
      path: common/oss
      ref: dart2
    version: '>=0.1.0'
  fs_shim: '>=1.0.2'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

dependency_overrides:
  tekartik_aliyun_oss:
    path: ../oss
